name: Continuous Integration

on: [push,pull_request]    # Will make the workflow run every time you push to any branch or create a open pull request 

jobs:
  docker:
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    paths-ignore:
    - 'README.md'
    steps:
    - name: Checkout
      uses: actions/checkout@v3 # Adds a step to checkout the repository code
    - name: Build container
      run: docker build --target test --tag todo-app-test .
    - name: Run container
      run: docker run todo-app-test    