name: Continuous Integration

on:
  push:
    paths-ignore:
      - README.md
    branches:
      - main
      - exercise-9  
  pull_request:
    paths-ignore:
      - README.md
    branches:
      - main
      - 'exercise**'           
jobs:
  docker-run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build container
        run: docker build --target test --tag todo-app-test .
      - name: Run container
        run: docker run todo-app-test
      - name: Check if docker-run-main can run
        if: ${{ github.event_name == 'push' && github.event_name.branches == 'exercise-9'}}
        run: docker-run-main      
  docker-run-main:
    needs: docker-run-test   
    runs-on: ubuntu-latest
    steps:
#     build and push docker container          
      - name: Checkout prod
        uses: actions/checkout@v3
      - name: Build prod container
        run: docker build --target production --tag todo-app-prod:latest .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Push Container to DockerHub
        run: docker push todo-app-prod:latest
      - name: Run container
        run: docker run todo-app-prod