name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch
jobs:
  docker:
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed

    steps:
    - name: Checkout
      uses: actions/checkout@v3 # Adds a step to checkout the repository code
    - name: Build container
      run: docker build --target test --tag todo-app-test .
    - name: Run container
      run: docker run todo-app-test