name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: check-build
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v3 # Adds a step to checkout the repository code
    - name: build container
#      workspace: GITHUB_WORKSPACE
#      working-directory: ${{ github.workspace }}
      run: docker compose up --build
    - name: check it is alive
      run: sleep 5 && curl --fail http://localhost:5100/
    - name: stop container
      run: docker compose down
#     args:
#    - ${{ inputs.who-to-greet }}
#    - name: Hello world       # Name of step
#      run: echo 'Hello world' # Command to run
#            - name: run C#
#              run: dotnet build
#            - name: run C# test
#              working-directory: ./DotnetTemplate.Web
#              run: dotnet test
#            - name: install and build npm
#              working-directory: ./DotnetTemplate.Web
#              run: npm install && npm run build
#            - name: run the TypeScript tests
#              working-directory: ./DotnetTemplate.Web
#              run: npm t
#            - name: run lint on TypeScript code
#              working-directory: ./DotnetTemplate.Web
#              run: npm run lint